name: Linty
on:
  pull_request:
  push:

jobs:
  linty:
    name: Linty
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create sonar-project.properties
        run: |
          echo "sonar.projectKey=neorv32" > $GITHUB_WORKSPACE/sonar-project.properties
          echo "sonar.sources=./rtl/core,./sim" >> $GITHUB_WORKSPACE/sonar-project.properties

      - name: Create linty_read.ys
        run: |
          cp $GITHUB_WORKSPACE/rtl/file_list_soc.f $GITHUB_WORKSPACE/.github/linty_read.ys
          sed -i 's/NEORV32_RTL_PATH_PLACEHOLDER/verific -work neorv32 -vhdl .\/..\/rtl/g' $GITHUB_WORKSPACE/.github/linty_read.ys
          echo "verific -L neorv32 -vhdl ./../rtl/core/neorv32_top.vhd" >> $GITHUB_WORKSPACE/.github/linty_read.ys

      - name: Create linty_hierarchy.ys
        run: |
          echo "hierarchy -top neorv32_top" > $GITHUB_WORKSPACE/.github/linty_hierarchy.ys

      - name: Cache
        uses: actions/cache@v3.3.0
        with:
          path: ~/.sonar/cache
          key: sonar
          restore-keys: sonar

      - name: Run Linty
        run: |
          docker run \
            -e SONAR_HOST_URL=https://oss.linty-services.com \
            -e SONAR_TOKEN="${{ secrets.LINTY_TOKEN }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e GITHUB_REPOSITORY_OWNER="$GITHUB_REPOSITORY_OWNER" \
            -e GITHUB_REPOSITORY="$GITHUB_REPOSITORY" \
            -e TABBY_CAD_LICENSE="$TABBY_CAD_LICENSE" \
            -v "$PWD:/usr/src" \
            lintyservices/linty-scanner:latest
        env:
          TABBY_CAD_LICENSE: ${{ secrets.TABBY_CAD_LICENSE }}

      - name: Debug
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: debug
          path: |
            ./bugfinder_workdir/
            ./.linty/
          include-hidden-files: true
